### ISSUE TITLE
Не сохраняются настройки нескольких кластеров работающих на одной платформе

### ISSUE THREAD

**Issue by GermanPavel** [YanSergey/OneS_ClusterAdmin#16]
Не сохраняются настройки второго, третьего и так далее кластера в config.json при закрытии программы, если эти кластеры работают на одной и той же версии платформы.

**Comment by YanSergey** [comment]
Проблема не воспроизводится.
Версия платформы не сохраняется в конфиге, и не может влиять на сохранение записи о сервере в целом.
Вероятно проблема в чем то другом.
