### ISSUE TITLE
Добавить возможность запускать через контексное меню скрипты

### ISSUE THREAD

**Issue by alexeyhachak** [YanSergey/OneS_ClusterAdmin#20]
Как предложение - расширить список команд контексного меню инфобазы. Например, формировать список команд на основании доступных файлов-скриптов. Передавая в скрипты параметры инфобазы, можно реализовать резервное копирование, обновления и т.д.

**Comment by YanSergey** [comment]
Сделал предварительную версию, можно потестировать.

В контекстном меню инфобазы формируется список скриптов из каталога scripts.
Список скриптов пока формируется при запуске программы (позже сделаю возможность обновить список).
В архиве несколько рабочих примеров скриптов.
Доступные параметры:
	%infobase%
	%serverName%
	%agentPort%
	%managerPort%
Параметры задаются через переменные окружения.

С остальными параметрами пока надо думать:
	- Логин/пароль инфобазы - хранится без привязки к базе, однозначно определить, какие Логин/пароль нам нужно не получится.
	- Диапазон РПХостов - неясно вообще нужен ли, и их можеет быть несколько на кластере (т.к. может быть несколько рабочих серверов)
	- Версия платформы - кажется, не все команды пакетного запуска конфигуратора смогут запускаться от exe-стартера ("C:\Program Files\1cv8\common\1cestart.exe"). Может понадобиться указывать конкретную версию exe (например, C:\Program Files\1cv8\8.3.20.1789\bin\1cv8.exe). Но RAS только с 8.3.16 отдает полную версию платформы сервера из 4 блоков.
	
Неизвестных прорамме параметров быть в скрипте сейчас не должно.
Думаю над тем, что бы при нахождении неизвестных параметров вывести пользователю форму для их ввода.
Это может быть чтото, что нельзя хранить в файле скрипта, либо различается для каждой базы.
Логин/пароль как раз можно будет в такой форме выбрать из списка сохраненных.

Развитие идеи скриптов:
	- запускать скрипты для нескольких инфобаз, через контекстное меню узла инфобаз (показать форму для выбора баз, для которых будет выполняться скрипт)
	- иерархию скриптов - для сервера, для кластера, для инфобаз. Пока непонятно нужно ли для сервера и кластера, как применять?
[OneS_ClusterAdmin_0.4.0.beta1.zip](https://github.com/YanSergey/OneS_ClusterAdmin/files/10148953/OneS_ClusterAdmin_0.4.0.beta1.zip)

**Comment by alexeyhachak** [comment]
Пробовали сегодня - работает! Спасибо!
